### ISSUE TITLE
Get rid of library calls within main code

### ISSUE THREAD

**Issue by bomeara** [bomeara/phrapl#3]
All packages should be in DESCRIPTION & NAMESPACE files. Note this isn't a simple matter of just deleting library lines; need to verify that the code works correctly after this change (unit testing would come to the rescue in this case...).

**Comment by ndjaxon** [comment]
Looks like you've already placed the dependencies in the description and namespace files. I've removed all "library" calls in code files. All dependencies pass the R CMD check fine and all the dependency functions were appropriately called when running though the phrapl tutorial.

**Comment by bomeara** [comment]
Yippee! [that's the professional term]. Closing this issue
